#include "fifo.h"
#include <stdlib.h>
#include <stdio.h>

/**** Tree of Nodes generated by DFS ****/
typedef struct tree
{
  struct node* root;
  int nNodes;
  int nEdges;
}Tree;

Tree* create_tree(Node* root);
void add_child(Tree* tree, Node* parent, Node* child);
void print_tree(Node* tree,int indent);
void print_indent(int indent);
